### ISSUE TITLE
"Create a sounddrop" page

### ISSUE THREAD

**Issue by berlintam** [sounddrop/sounddrop#2]
#### Step 1
- [ ] "Create a Sounddrop" page. We currently already have a `/login` path, but this should be renamed to something like `/create` and should lead to a custom page which does the following:
- [ ] page asks people to first connect with soundcloud = > redirects them to soundcloud to login

This is already half done using the `/login` path. But these routes need to be re-named 'n whatnot. 
#### Step 2
- [ ] Add text field to create a new place section at bottom of the `stories/new` page.

**Comment by berlintam** [comment]
questions for @sferik @starkcoffee @nynnejc :

We've said that we want to be able to have a text field where one can enter a url for a soundcloud sound. At the moment, we are saving the soundcloud track id to the database. If we offer the user the option to instead enter a soundcloud url, how do we deal with this? Options include:
- create a new attribute on drop called 'sc_url' and just save that instead (the whole url for a track). However we then run into validation problems because a drop validates the presence of a sc_track id. I don't know if it's possible to validate EITHER a track id OR a track url. But I'm sure someone here will be able to clear that up for us :)
- enter the sc_url and then somehow pull the sc_track id from it and save that in the database, thereby solving the validation problems and also removing the necessity for a new attribute on drop. 

I'm in favour of option 2, i just don't know how to do it. But never fear, @WlFranzi shall do it :smile:

**Comment by nynnejc** [comment]
Hm its hard to tell what is the most functional? Let's discuss!

**Comment by berlintam** [comment]
:+1: !

**Comment by starkcoffee** [comment]
Hi! Good catch. The future idea was that artist can connect their
SoundCloud track and choose them from a drop down list, and in that case we
would have the track ID from the api.

Idea 3: there is a soundcloud API endpoint that lets you find the id fron a
track url. we could use that to find out the ID, and that also could be how
we validate that it's a valid url

**Comment by berlintam** [comment]
yup - however, @WlFranzi made a good point that sounddrop can also be used by non-artists, and in such cases, people can enter the URLs of soundcloud tracks and connect those to a map/QR code. In cases like this, they won't have a dropdown list of their own tracks to choose from, instead they'd want to enter the track id/url of someone else. This is something I'd never thought about before, but is a cool option/idea.

This is connected to https://github.com/rubyherzlein/rubyherzleintoDo/issues/2

**Comment by starkcoffee** [comment]
:thumbsup:

**Comment by starkcoffee** [comment]
Done! :bouquet:
