### ISSUE TITLE
Roadmap for September

### ISSUE THREAD

**Issue by WlFranzi** [sounddrop/sounddrop#33]
<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Goals</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Aug 24</th>
      <td>Finalize creating the drop feature. Add menu item for creating drops.</td>
    </tr>
    <tr>
      <th>Aug 31</th>
      <td>:tada: :es: :gem: :palm_tree: :confetti_ball:</td>
    </tr>
    <tr>
      <th>Sept 7</th>
      <td>Allow artists to add geotags.</td>
    </tr>
    <tr>
      <th>Sept 14</th>
      <td>Show a map view of drops.</td>
    </tr>
    <tr>
      <th>Sept 21</th>
      <td>Styling</td>
    </tr>
  </tbody>
</table>

**Comment by berlintam** [comment]
![pony](https://cloud.githubusercontent.com/assets/4237285/9448594/c358f092-4a9d-11e5-9324-c802bea47814.gif)
