### ISSUE TITLE
Drop index page

### ISSUE THREAD

**Issue by berlintam** [sounddrop/sounddrop#48]
It could use some love.... perhaps we could order by created_at and have a drop stream there where we show the latest drops that were uploaded?

**Comment by berlintam** [comment]
Or perhaps it would be cool to show a big map & display all the drops on the map.... if we have the user's location we can customize it to show drops around them, if not, we can show the world. I guess it would look something like this http://storymap.ie/ (minus the sidebar & the fancy animation, and of course visualize our logo....)

@nynnejc @starkcoffee @Powerglove @aydamacink  what do you think? Maybe we can collect some ideas here....

**Comment by langjoh** [comment]
@berlintam I think that is a good idea. As long as there are not too many drops, the world map probably looks good, but as soon as there are more than 1,000 drops, you might not see the map anymore because of all the drops?! So it might be a good idea to limit it to the user's location. But at the same time, not everbody wants to be tracked all the time...

**Comment by berlintam** [comment]
related to https://github.com/sounddrop/sounddrop/issues/81
- map w/ drops should be new root path, and current content on landing page should be moved to an about page. 

Additional info:
- when a drop is clicked on, user should be redirected to the drop#show page.

**Comment by berlintam** [comment]
Apparently some browsers ask you if you want to share your location with them. There’s I guess a browser api for that. so it might be kind of cool to look into that! So we can show a localized map to the user when they agree to share their location w/ the browser, otherwise we don’t. That’s probably a better way to go.  That being said, I really have no idea how that whole thing works & can’t give much more insight to it at the moment… 

Also, despite the fact we have barely any drops at the moment, once we become super app famous, we'll have lots, and we won't want to cram up the app with all of them. So how about for now we show the latest 20 uploaded drops on the map. We can worry about how we'll show all of them later. 

Does that sound good? Do you have any ideas about how we could allow the user to continue on and see all the drops?

**Comment by aydamacink** [comment]
Provided the app becomes super famous, do we really want the user to see AAaaLL drops?

**Comment by berlintam** [comment]
well... i guess there in theory has to be a way for the user to view all the drops -  in the future some sort of scrolling/filtering/tagging/search thing will probably be necessary. But that's waaaay in the future. 
OoOoOohhhh maybe this can also somehow be combined with the tagging feature you two wanted to work on! such ideas! Anyway, i'm getting ahead of myself....
