### ISSUE TITLE
Spec for first api endpoint

### ISSUE THREAD

**Issue by starkcoffee** [sounddrop/sounddrop#67]
**Request**
GET http://sounddrop.audio/api/drops

**Response when there are tracks**
HTTP OK 200

``` json
[
{ 
  "title": "My cool track", 
  "sc_track": 123456,
   "place": {
       "name": "SoundCloud office",
       "latitude": 53.2,
       "longitude": 13.4
   }
},
{ 
  "title": "Over the rainbow", 
  "sc_track": 67894542,
   "place": {
       "name": "Berlin wall",
       "latitude": 53.3,
       "longitude": 13.45
   }
}
]
```

**Response when no tracks**
HTTP OK 200

``` json
[]
```

**Comment by aydamacink** [comment]
For now it looks like this, so we have to make the corresponding adjustments: 

[{"id":1,"title":"Coffee Machine","sc_track":187471639,"user_id":null,"created_at":"2016-07-01T08:25:27.171Z","updated_at":"2016-07-01T08:25:27.171Z","place_id":1},{"id":2,"title":"Brewing Coffee for engineers","sc_track":187472172,"user_id":null,"created_at":"2016-07-01T08:25:27.175Z","updated_at":"2016-07-22T14:31:11.435Z","place_id":7},{"id":3,"title":"Art installation","sc_track":187472038,"user_id":null,"created_at":"2016-07-01T08:25:27.179Z","updated_at":"2016-07-01T08:25:27.179Z","place_id":1},{"id":4,"title":"CHAPELIER FOU - #01 Bulbs","sc_track":257403369,"user_id":null,"created_at":"2016-07-04T13:14:06.468Z","updated_at":"2016-07-04T13:14:06.468Z","place_id":2},{"id":5,"title":"CHAPELIER FOU - #01 Bulbs","sc_track":257403369,"user_id":null,"created_at":"2016-07-04T14:10:20.446Z","updated_at":"2016-07-04T14:10:20.446Z","place_id":3},{"id":6,"title":"We The Kings \u0026 Elena Coats - \"Sad Song\"","sc_track":125292662,"user_id":null,"created_at":"2016-07-04T14:12:33.830Z","updated_at":"2016-07-04T14:12:33.830Z","place_id":5}]
