### ISSUE TITLE
Retrieve drops near specific location as JSON

### ISSUE THREAD

**Issue by rstammer** [sounddrop/sounddrop#70]
@aydamacink and @Powerglove have started working on a first HTTP-endpoint for retrieving drops as JSON. This issue is a proposal to work on top of that. 
### User story

Say you're visiting a city you've never been to in a country whose language is new to you. And you'd like to explore some public places. You may ask yourself if there are some drops near your current location that may help you out with explanations or nice sounds or inspirations. Or audio messages from earlier tourists :)

It would be very to cool to have a neat mobile app delivering the drops near your location. As a first step towards this direction, accessing the drops surrounding you via JSON would be a solid start. 
### Some technical notes on locations
- a "location" could be simply interpreted as pair of `Float` values named [latitude and longitude](https://en.wikipedia.org/wiki/Geographic_coordinate_system)
- We recently talked about the gem [geocoder](https://github.com/alexreisner/geocoder). Note that besides its main purpose of retrieving lat/long-values you can do further fancy things with it, especially distance calculations. It contains a module `Geocoder::Calculations`, see [this test file](https://github.com/alexreisner/geocoder/blob/e9d7100009ff7be15a9d5a3e7578ceee0e047bb4/test/unit/calculations_test.rb) for example usage. I can imagine it could be a helpful tool. 
- One _could_ also do calculations concerning distances directly on the database layer. For example there is [an extension for PostgresSQL](https://www.postgresql.org/docs/9.3/static/earthdistance.html), maybe there are similar tools for other RDBMs like SQLite out there (just a thought that needs verification and further research, I'm not sure if it is a good idea)
### Routing/Endpoints/Input

There are several possibilities to organize your routing and controllers for that. To start with
routing, I could imagine:

```
GET /api/drops?lat=53.450257&long=11.953531

and/or

GET /api/drops/berlin

and/or

GET /api/drops/berlin?radius=25

and/or

GET /api/drops?city=berlin&radius=5

and/or

GET /api/drops?lat=53.450257&long=11.953531&radius=450
```

I can imagine that there are other clever solutions possible. Let's see what fits to sounddrop best. 
### First Roadmap suggestion
- [x] Research: How do other web applications / RESTful APIs solve a similar problem?
- [x] Design a meaningful routing for this functionality
- [x] Boil down your first thoughts as (request) specs (feel free to experiment here!)
- [x] Think about the "output" a.k.a  the rendered JSON
- [x] Think about the sounddrop data structures: How do drops relate to locations?  How can you collect drops near a specific collection? 
- [x] Make your tests pass :shipit: 

Disclaimer: This is a proposal and somewhat a draft. Every point is worth a discussion :)

**Comment by aydamacink** [comment]
The request specs are passing but somewhere else in the app there are some problems and the Travis tests are failing, Maybe due to this: Failure/Error: visit "/stats"
          Selenium::WebDriver::Error::WebDriverError:
            Could not find Firefox binary (os=macosx). Make sure Firefox is installed or set the path manually with Selenium::WebDriver::Firefox::Binary.path=
