### ISSUE TITLE
Sound does not Work in Chrome

### ISSUE THREAD

**Issue by aydamacink** [sounddrop/sounddrop#75]
There seems to be an issue with the SoundCloud API and Chrome: 

https://github.com/soundcloud/soundcloud-javascript/issues/39

**Comment by langjoh** [comment]
@starkcoffee @berlintam Within this issue, somebody explains a workaround and we were wondering if we should try it? We would either try to remove 'rtmp' from the options hash or pass a completely new options hash.

**Comment by berlintam** [comment]
wow, good find!!! ya, I guess try the workarounds, it doesn't seem like it'll get fixed in the near future, so this'll be a good lesson in trying-random-stuff-from-the-internet-until-it-works :)

**Comment by langjoh** [comment]
The workaround only works with the latest SoundCloud API version, so we will try this #76

**Comment by langjoh** [comment]
Problem will be solved after merging #78 aka updating the Sounscloud API #76
