### ISSUE TITLE
rename & delete stuff from stories

### ISSUE THREAD

**Issue by berlintam** [sounddrop/sounddrop#8]
We've decided that we should not really store any data which can be pulled from soundcloud in the app. We shall do the following:
- [x] rename `stories` to `drops`
- [x] delete `title` from the story model (aka the drop model)
- [x] not save any soundcloud data in our drop model! We can pull it all directly from soundcloud
- [x] think about renaming playlists to something else. ideas: stream, cloud, collection, puddle, pool, storm, lake, river etc....

Sounddrops are soundcloud track ids and locations. That's it!

**Comment by berlintam** [comment]
@WlFranzi unfortunately this means we're going to have to re-think your PR https://github.com/sounddrop/sounddrop/pull/6. Instead of storing the description, we're instead just going to pull it from soundcloud. @starkcoffee will fill you in :)

**Comment by starkcoffee** [comment]
in progress! @WlFranzi and I started this. :shaved_ice:

**Comment by berlintam** [comment]
amazing!

**Comment by berlintam** [comment]
part of this is handled here: https://github.com/sounddrop/sounddrop/pull/9
