### ISSUE TITLE
search drops by category (tag)

### ISSUE THREAD

**Issue by langjoh** [sounddrop/sounddrop#99]
Users should be able to search for drops of a certain category only. This could be achieved with checkboxes next to the map on the landing page. If you check a box, the page/map reloads and only shows drops with the selected tag.

**Comment by berlintam** [comment]
An example of this is https://www.makerist.de/works

**Comment by langjoh** [comment]
- [x] write Request Specs
- [x] limit Drops by selected tag (in controller)
- [x] add select box, page needs to reload after select
- [x] render selected drops on index page

**Comment by berlintam** [comment]
closed with https://github.com/sounddrop/sounddrop/pull/108
